//
//  DetailViewInteractor.swift
//  Colors
//
//  Created Vic Rmz on 06/09/24.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by UPAX Zeus
//

import UIKit

class DetailViewInteractor: DetailViewInteractorInputProtocol {
    weak var presenter: DetailViewInteractorOutputProtocol?
}
