//
//  DetailViewPresenter.swift
//  Colors
//
//  Created Vic Rmz on 06/09/24.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by UPAX Zeus
//

import UIKit

class DetailViewPresenter {
    weak private var view: DetailViewViewProtocol?
    var interactor: DetailViewInteractorInputProtocol?
    private let router: DetailViewWireframeProtocol

    init(interface: DetailViewViewProtocol, interactor: DetailViewInteractorInputProtocol?, router: DetailViewWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
}

extension DetailViewPresenter: DetailViewPresenterProtocol {
    
}

extension DetailViewPresenter: DetailViewInteractorOutputProtocol {
    
}
