//
//  DetailViewProtocols.swift
//  Colors
//
//  Created Vic Rmz on 06/09/24.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by UPAX Zeus
//

import Foundation

//MARK: Presenter -> Router
protocol DetailViewWireframeProtocol: AnyObject {
}

//MARK: View -> Presenter
protocol DetailViewPresenterProtocol: AnyObject {
    var interactor: DetailViewInteractorInputProtocol? { get set }
}

//MARK: Interactor -> Presenter
protocol DetailViewInteractorOutputProtocol: AnyObject {
    
}

//MARK: Presenter -> Interactor
protocol DetailViewInteractorInputProtocol: AnyObject {
    var presenter: DetailViewInteractorOutputProtocol?  { get set }
}

//MARK: Presenter -> View
protocol DetailViewViewProtocol: AnyObject {
    var presenter: DetailViewPresenterProtocol?  { get set }
}
