//
//  DetailViewView+Layout.swift
//  Colors
//
//  Created Vic Rmz on 06/09/24.
//  Template generated by UPAX Zeus
//

import UIKit

extension DetailViewView {
    
    func addViews() {
        addSubview(imageDetailViewColor)
        addSubview(descriptionDetailViewColor)
    }
    
    func setupConstraints() {
        
        imageDetailViewColor.addAnchorsAndCenter(centerX: true, centerY: nil, width: 150, height: 150, left: nil, top: 120, right: nil, bottom: nil)
        
        
        descriptionDetailViewColor.addAnchorsAndCenter(centerX: true, centerY: nil, width: width-100, height: 150, left: nil, top: 0, right: nil, bottom: nil, withAnchor: .top, relativeToView: imageDetailViewColor)
        
    }
}
