//
//  DetailViewView.swift
//  Colors
//
//  Created Vic Rmz on 06/09/24.
//  Template generated by UPAX Zeus
//

import UIKit

class DetailViewView: UIView {
    // MARK: Child views
    
    lazy var imageDetailViewColor : UIImageView = {
        var image = UIImageView()
        image.layer.cornerRadius = 5
        return image
    }()
    
    lazy var descriptionDetailViewColor : UILabel = {
        var description = UILabel()
        description.font = .preferredFont(forTextStyle: .body)
        description.numberOfLines = 0
        description.textAlignment = .center
        return description
    }()
    
    
    // MARK: Initializers
    init() {
        super.init(frame: .zero)
        addViews()
        setupConstraints()
        backgroundColor = .white
    }
    
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}
