//
//  ColorViperPresenter.swift
//  Colors
//
//  Created Vic Rmz on 04/09/24.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by UPAX Zeus
//

import UIKit

class ColorViperPresenter {
    weak private var view: ColorViperViewProtocol?
    var interactor: ColorViperInteractorInputProtocol?
    private let router: ColorViperWireframeProtocol

    init(interface: ColorViperViewProtocol, interactor: ColorViperInteractorInputProtocol?, router: ColorViperWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
}

extension ColorViperPresenter: ColorViperPresenterProtocol {
    func goToDetailView(info : Photo) {
        router.goToDetailView(info: info)
    }
    
    func getData() {
        interactor?.getData()
    }
    
    
}

extension ColorViperPresenter: ColorViperInteractorOutputProtocol {
    
    func gettedData(data: [Photo]) {
        view?.gettedData(data: data)
    }
    
    
}
