//
//  ColorViperView.swift
//  Colors
//
//  Created Vic Rmz on 04/09/24.
//  Template generated by UPAX Zeus
//

import UIKit

class ColorViperView: UIView {
    
    lazy var colorList : UITableView = {
        var table = UITableView()
        table.backgroundColor = .white
        table.layer.cornerRadius = 10
        return table
    }()
    
    lazy var progressView: UIProgressView = {
        let progress = UIProgressView(progressViewStyle: .default)
        progress.isHidden = true
        return progress
    }()
    
    init() {
        super.init(frame: .zero)
        self.backgroundColor = .white
        addViews()
        setupConstraints()
        
    }
    
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}
