//
//  ColorViperView+Layout.swift
//  Colors
//
//  Created Vic Rmz on 04/09/24.
//  Template generated by UPAX Zeus
//

import UIKit

extension ColorViperView {
    func addViews() {
        addSubview(colorList)
        addSubview(progressView)
    }
    
    func setupConstraints() {
        colorList.addAnchors(left: 20, top: 100, right: 20, bottom: 0)
        progressView.addAnchorsAndCenter(centerX: true, centerY: true, width: 80, height: 80, left: nil, top: nil, right: nil, bottom: nil)
    }
}
