//
//  ColorViperRouter.swift
//  Colors
//
//  Created Vic Rmz on 04/09/24.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by UPAX Zeus
//

import UIKit

class ColorViperRouter: ColorViperWireframeProtocol {    
    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        let view = ColorViperViewController()
        let interactor = ColorViperInteractor()
        let router = ColorViperRouter()
        let presenter = ColorViperPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
    
    func goToDetailView (info : Photo){
        let detailViewController = DetailViewRouter.createModule(info: info)
        viewController?.navigationController?.pushViewController(detailViewController, animated: true)
    }
}
